import { SnackbarProvider } from "@/providers/SnackbarProvider";
import { HtmlThemeProvider } from "@/providers/ThemeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <HtmlThemeProvider lang="ja">
      <body className={inter.className}>
        <SnackbarProvider>
          <div id="header" />
          <main>{children}</main>
        </SnackbarProvider>
      </body>
    </HtmlThemeProvider>
  );
}
